POST http://localhost:8080/api/todos
Accept: application/json
Content-Type: application/json

{
  "title": "Poznać Rusta",
  "description": "Trudna sprawa"
}

###

GET http://localhost:8080/api/todos/e4f221ba-e0bf-4b97-b9db-a536c262c8a8
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/todos?completed=false
Accept: application/json
Content-Type: application/json
